namespace DnaBrasilApi.Application.Laudos.Queries;
public class DesempenhoDto
{
    public int ScoreTalentoEsportivo { get; init; }
    public int ScoreSaude { get; init; }
    public int ScoreVida { get; init; }
    public int ScoreVocacional { get; init; }
    public int ScoreSaudeBucal { get; init; }
    public int ScoreConsumoAlimentar { get; init; }
    public int ScoreMatematica { get; init; }
    public int ScorePortugues { get; init; }
    public int ScoreDna { get; init; }
    public string? AvisoVelocidade { get; init; }
    public string? PercentualVelocidade { get; init; }
    public string? AvisoImpulsao { get; init; }
    public string? PercentualImpulsao { get; init; }
    public string? AvisoShuttleRun { get; init; }
    public string? PercentualShuttleRun { get; init; }
    public string? AvisoFlexibilidadeMuscular { get; init; }
    public string? PercentualFlexibilidadeMuscular { get; init; }
    public string? AvisoForcaMembrosSup { get; init; }
    public string? PercentualForcaMembrosSup { get; init; }
    public string? AvisoAptidaoCardio { get; init; }
    public string? PercentualAptidaoCardio { get; init; }
    public string? AvisoPrancha { get; init; }
    public string? PercentualPrancha { get; init; }
    public string? AvisoImc { get; init; }
    public string? AvisoBemEstar { get; init; }
    public string? AvisoAutoestima { get; init; }
    public string? AvisoFamilia { get; init; }
    public string? AvisoContexto { get; init; }
    public string? AvisoSaudeBucal { get; init; }
    public string? AvisoConsumoAlimentar { get; init; }
    public string? AvisoPortugues { get; init; }
    public string? AvisoMatematica { get; init; }
    public DateTimeOffset? DataTalentoEsportivo { get; init; }
    public DateTimeOffset? DataSaude { get; init; }
    public DateTimeOffset? DataVida { get; init; }
    public DateTimeOffset? DataVocacional { get; init; }
    public DateTimeOffset? DataConsumoAlimentar { get; init; }
    public DateTimeOffset? DataSaudeBucal { get; init; }
    public DateTimeOffset? DataMatematica { get; init; }
    public DateTimeOffset? DataPortugues { get; init; }
    public string? TextoVelocidade { get; init; }
    public string? TextoImpulsao { get; init; }
    public string? TextoShuttleRun { get; init; }
    public string? TextoFlexibilidadeMuscular { get; init; }
    public string? TextoForcaMembrosSup { get; init; }
    public string? TextoAptidaoCardio { get; init; }
    public string? TextoPrancha { get; init; }
    public string? TextoImc { get; init; }
    public string? TextoBemEstar { get; init; }
    public string? TextoAutoestima { get; init; }
    public string? TextoFamilia { get; init; }
    public string? TextoContexto { get; init; }
    public string? TextoVocacional { get; init; }
    public string? TextoConsumoAlimentar { get; init; }
    public string? TextoSaudeBucal { get; init; }
    public string? TextoMatematica { get; init; }
    public string? TextoPortugues { get; init; }
    public string? SerieAluno { get; init; }
    public string? TurmaAluno { get; init; }
}
